"""Users is_active removed

Revision ID: 05a15694cd7c
Revises: 26b7ff49e7de
Create Date: 2025-02-09 17:56:32.762040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05a15694cd7c'
down_revision: Union[str, None] = '26b7ff49e7de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
