"""Changed to Declarative base

Revision ID: 26b7ff49e7de
Revises: ca401880ce43
Create Date: 2025-02-09 17:54:06.361652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26b7ff49e7de'
down_revision: Union[str, None] = 'ca401880ce43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
