"""Two factor created at changed to on update

Revision ID: 6ec8c27f818e
Revises: 05a15694cd7c
Create Date: 2025-02-10 09:57:57.099654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ec8c27f818e'
down_revision: Union[str, None] = '05a15694cd7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
